### ISSUE TITLE
Add GNOME Asia to the calendar

### ISSUE THREAD

**Issue by matthiasclasen** [OSAS/rh-events#187]
name: GNOME Asia
location: Delhi, India
start: 2016-04-21
end: 2016-04-24
description: |GNOME.Asia Summit is the featured annual GNOME Conference in Asia. The event focuses primarily on the GNOME desktop, but also covers applications and the development platform tools. It brings together the GNOME community in Asia to provide a forum for users, developers, foundation leaders, governments and businesses to discuss the present technology and future developments.

  Additional details about the conference are available
  [on the conference website](http://2016.gnome.asia).

**Comment by bproffitt** [comment]
Will add a file.

**Comment by bproffitt** [comment]
File added.
