### ISSUE TITLE
Add GUADEC to the calendar

### ISSUE THREAD

**Issue by matthiasclasen** [OSAS/rh-events#188]
name: GUADEC
location: Karlsruhe, Germany 
start: 2016-08-12
end: 2016-08-14
description: GUADEC is the main conference for GNOME users, developers, foundation leaders, individuals, governments and businesses worldwide.   

  Additional details about the conference are available
  [on the conference website](http://guadec.org/).

**Comment by bproffitt** [comment]
Will add a file.

**Comment by bproffitt** [comment]
File added.
