### ISSUE TITLE
DevConf.cz 2017 - Brno CZ

### ISSUE THREAD

**Issue by kejbaly2** [OSAS/rh-events#231]
name: DevConf.cz
location: Brno, Czech Republic
start: 2017-01-27
end: 2017-01-29
description: |
  DevConf.cz 2017 is the 9th annual, free and open 3-day open-source Fedora Linux and JBoss community conference for Red Hat and community developers, DevOps, testers, and documentation writers, organized to sync, share, and hack on upstream projects with the community in the beautiful city of Brno, Czech Republic.

  Additional details about the conference are available
  [at devconf.cz](https://devconf.cz).

**Comment by bproffitt** [comment]
I just updated this this morning; does it need further revision?

BKP

**Comment by kejbaly2** [comment]
Oh, nice! I didn't notice. Let me check... found it! Nice. Perfect! Sorry
for the noise. Thanks for being proactive about it.

-Chris
