### ISSUE TITLE
how can I build CentOS 8 iso dvd with aarch64?

### ISSUE THREAD

**Issue by GitSoftwareNow** [OSAS/rh-events#430]
name: CONFERENCE NAME HERE
location: SOMEPLACE, COUNTRY
start: 2016-11-31
end: 2016-11-31
description: |
  EDIT this Markdown block of text with your conference info.

  If there are talks, please list them below. Otherwise, feel free
  to remove `talks:` and everything after.

  Additional details about the conference are available
  [on the conference website](http://SOMECONFERENCE.ORG/).

talks:

- title: FIRST TALK
  speaker: SOME NAME
  start: 2013-11-31 11:00 PDT
  end: 2013-11-31 11:30 PDT
  description: |
    EDIT and ADD your own description here, using Markdown.
    Lists are supported, too:

    * Foo
    * Bar

- title: SECOND TALK
  speaker: SOMEBODY ELSE
  start: 2013-11-31 12:00 PDT
  end: 2013-11-31 12:30 PDT
  description: |
    EDIT and ADD your own description here, using Markdown.

**Comment by bproffitt** [comment]
Spam.
